name: Andromeda
author: MrOnlineCoder
version: 1.0.0
main: com.mronlinecoder.AndromedaCommands
commands:
  ragequit:
    description: Ragequit from server
    aliases: rq
    permission: andromeda.ragequit
  info:
    description: Displays info about a player
    permission: andromeda.info
  ban:
    description: Bans a player
    permission: andromeda.ban
  kick:
    description: Kicks a player
    permission: andromeda.kick
  rank:
    description: Changes player's rank
    permission: andromeda.rank
  join:
    description: Joins the world
    permission: andromeda.join
  review:
    description: Requests for review 
    permission: andromeda.review
  unban:
    description: Unbans a player
    permission: andromeda.unban
  bring:
    description: Teleports player to you
    permission: andromeda.bring